spin_manifest_version = 2

[application]
name = "moscow-time"
version = "0.1.0"
authors = ["Mahmoud Hassan <selysecr332@users.noreply.github.com>"]
description = "Lab 12 — Moscow time endpoint (Spin + TinyGo)"

[[trigger.http]]
route = "/time"
component = "moscow-time"

[component.moscow-time]
source = "main.wasm"
allowed_outbound_hosts = []

[component.moscow-time.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
